FROM ubuntu:16.04
MAINTAINER Mosaicwang <mosaicwang@gmail.com>
RUN apt-get update 
RUN apt-get install wget
RUN wget https://storage.googleapis.com/kubernetes-helm/helm-v2.10.0-linux-amd64.tar.gz

