FROM gcr.io/google_containers/heapster-amd64:v1.5.3
MAINTAINER Mosaicwang <mosaicwang@gmail.com>
RUN apt-get update &apt-get install wget
RUN wget https://storage.googleapis.com/kubernetes-helm/helm-v2.10.0-linux-amd64.tar.gz

